In [1]:
import pandas as pd
import regex as re
import os
from pathlib import Path
from itertools import chain
from collections import Counter

In [2]:
df_file_lifecycle = pd.read_json('../../DATASETS/excalidraw/file_lifecycle.json')
df_file_lifecycle.columns

Index(['files', 'total_commits', 'total_changes', 'generated_at',
       'repository_path', 'skipped_unmerged'],
      dtype='object')

In [3]:
df_file_lifecycle = df_file_lifecycle.reset_index()
df_file_lifecycle = df_file_lifecycle.rename(columns={'index': 'FILE_PATH'})
df_file_lifecycle.sample()

,FILE_PATH,files,total_commits,total_changes,generated_at,repository_path,skipped_unmerged
1227,packages/excalidraw/fonts/woff2/Assistant/Assi...,[{'commit_hash': 'b479f3bd6553be5730e3b60beb8e...,5137,26822,2026-01-14 16:04:31.989647+00:00,/home/akbar/Jupyter_Notebooks/SOFTWARE_ARCHEOL...,0

In [4]:
df_file_lifecycle['total_changes'].sample(3) # all the same?

784     26822
1889    26822
1549    26822
Name: total_changes, dtype: int64

In [5]:
df_file_lifecycle['files'][88][0]

{'commit_hash': 'ce43cdf3650f576250a2a1d7bdcb589e60f0cdb1',
 'timestamp': 1767788808,
 'datetime': '2026-01-07T12:26:48+00:00',
 'operation': 'M',
 'author_name': 'Mark Tolmacs',
 'author_email': 'mark@lazycat.hu',
 'commit_subject': 'fix: Possible test timeout'}

In [6]:

Counter(list(chain(*df_file_lifecycle['files'].apply(lambda x: [i['operation'] for i in x]))))

Counter({'D': 366, 'M': 23491, 'R': 1243, 'A': 1722})

In [7]:
df_file_lifecycle['generated_at'].value_counts()

generated_at
2026-01-14 16:04:31.989647+00:00    2739
Name: count, dtype: int64

In [8]:
df_file_lifecycle['repository_path'].value_counts()

repository_path
/home/akbar/Jupyter_Notebooks/SOFTWARE_ARCHEOLOGY/excalidraw    2739
Name: count, dtype: int64

In [9]:
df_file_lifecycle['skipped_unmerged'].value_counts()

skipped_unmerged
0    2739
Name: count, dtype: int64

In [10]:
df_file_lifecycle['total_changes'].value_counts()

total_changes
26822    2739
Name: count, dtype: int64

In [11]:
df_file_lifecycle['total_commits'].value_counts()

total_commits
5137    2739
Name: count, dtype: int64

In [12]:
Counter(list(chain(*df_file_lifecycle['files'].apply(lambda x: [i['author_email'] for i in x])))).most_common(30)

[('aakansha1216@gmail.com', 4499),
 ('luzar.david@gmail.com', 2936),
 ('marcel@excalidraw.com', 2775),
 ('lipiridis@gmail.com', 2214),
 ('77840495+excalibot@users.noreply.github.com', 2169),
 ('5153846+dwelle@users.noreply.github.com', 1636),
 ('ryan.weihao.di@gmail.com', 1471),
 ('49699333+dependabot[bot]@users.noreply.github.com', 1169),
 ('mark@lazycat.hu', 914),
 ('viczian.zsolt@gmail.com', 893),
 ('27856297+dependabot-preview[bot]@users.noreply.github.com', 520),
 ('arnostpleskot@gmail.com', 436),
 ('1852529+DanielJGeiger@users.noreply.github.com', 414),
 ('vjeuxx@gmail.com', 329),
 ('38168628+barnabasmolnar@users.noreply.github.com', 284),
 ('petehunt@users.noreply.github.com', 234),
 ('git@twopointzero.us', 214),
 ('me@gasim.xyz', 209),
 ('konmpar@gmail.com', 156),
 ('arun4033622@gmail.com', 154),
 ('bboytx@gmail.com', 149),
 ('steveruizok@gmail.com', 133),
 ('steiner.thomas@gmail.com', 129),
 ('dai-shi@users.noreply.github.com', 128),
 ('Faustino.kialungila@gmail.com', 99),
 ('833927+pshihn@users.noreply.github.com', 91),
 ('xixixao@seznam.cz', 90),
 ('barnabas@excalidraw.com', 86),
 ('marcelmraz@seznam.cz', 72),
 ('artur@excalidraw.com', 67)]

In [13]:
dict(df_file_lifecycle['FILE_PATH'].apply(lambda x: Path(x).parent.as_posix()).value_counts().sample(10))

{'packages/excalidraw/components/Stats': np.int64(17),
 'packages/excalidraw/tests/__snapshots__': np.int64(14),
 'packages/excalidraw': np.int64(86),
 'examples/with-nextjs/src/app': np.int64(3),
 'src/packages/extensions/patches': np.int64(1),
 'packages/common/src/__snapshots__': np.int64(1),
 'dev-docs/src/theme/ReactLiveScope': np.int64(1),
 'packages/excalidraw/eraser': np.int64(1),
 'packages/element/src/__tests__/__snapshots__': np.int64(1),
 'examples/excalidraw/components/sidebar': np.int64(2)}

In [14]:
list_01 = ['packages/excalidraw/example/sidebar',
 'src/locales',
 'src/fonts',
 'packages/utils/src/geometry',
 'examples/with-nextjs/src/app',
 'packages/excalidraw/fonts/woff2/Lilita',
 'packages/excalidraw/components/LaserTool',
 'packages/excalidraw/eraser',
 'packages/excalidraw/components/Stats',
 'public/backgrounds']

In [15]:
# Example
df_file_lifecycle[df_file_lifecycle['FILE_PATH'].apply(lambda x: Path(x).parent.as_posix() in list_01)].sample()

,FILE_PATH,files,total_commits,total_changes,generated_at,repository_path,skipped_unmerged
1985,src/locales/tr-TR.json,[{'commit_hash': 'ab1bcc761565a4b82f72437931c6...,5137,26822,2026-01-14 16:04:31.989647+00:00,/home/akbar/Jupyter_Notebooks/SOFTWARE_ARCHEOL...,0

In [16]:
df_file_lifecycle['PARENT_DIR'] = df_file_lifecycle['FILE_PATH'].apply(lambda x: Path(x).parent.as_posix())

In [17]:
df_file_lifecycle['files'][0]

[{'commit_hash': 'b9a255407fc5e68893016de56057614da26df50c',
  'timestamp': 1768065314,
  'datetime': '2026-01-10T17:15:14+00:00',
  'operation': 'D',
  'author_name': 'David Luzar',
  'author_email': '5153846+dwelle@users.noreply.github.com',
  'commit_subject': 'refactor: update SCSS syntax & remove open-color dep (#10633)'},
 {'commit_hash': '432a46ef9ee13afe47530e857a259acde4d0fd59',
  'timestamp': 1742999099,
  'datetime': '2025-03-26T14:24:59+00:00',
  'operation': 'M',
  'author_name': 'Marcel Mraz',
  'author_email': 'marcel@excalidraw.com',
  'commit_subject': 'refactor: separate elements logic into a standalone package (#9285)'},
 {'commit_hash': '21ffaf4d76bf8554c3ba5561ab8ff41ce89b55fa',
  'timestamp': 1741789411,
  'datetime': '2025-03-12T14:23:31+00:00',
  'operation': 'M',
  'author_name': 'Marcel Mraz',
  'author_email': 'marcel@excalidraw.com',
  'commit_subject': 'refactor: auto ordered imports (#9163)'},
 {'commit_hash': 'ecef5d12f4af4f70e240fc54fb626c16d005eee3',
  'timestamp': 1740757749,
  'datetime': '2025-02-28T15:49:09+00:00',
  'operation': 'M',
  'author_name': 'Marcel Mraz',
  'author_email': 'marcel@excalidraw.com',
  'commit_subject': 'chore: release @excalidraw/excalidraw@18.0.0  🎉 (#9127)'},
 {'commit_hash': '1ed53b153cd09ef32e45304ab52b7d32fbe02605',
  'timestamp': 1715158310,
  'datetime': '2024-05-08T08:51:50+00:00',
  'operation': 'M',
  'author_name': 'Aakansha Doshi',
  'author_email': 'aakansha1216@gmail.com',
  'commit_subject': 'build: enable consistent type imports eslint rule (#7992)'},
 {'commit_hash': 'd6cd8b78f11742e9107dd4cd9cee564120ae599b',
  'timestamp': 1702360971,
  'datetime': '2023-12-12T06:02:51+00:00',
  'operation': 'M',
  'author_name': 'Aakansha Doshi',
  'author_email': 'aakansha1216@gmail.com',
  'commit_subject': 'build: decouple package deps and introduce yarn workspaces (#7415)'},
 {'commit_hash': '741d5f1a187438b46d4482cdc3ca0f8fde4f4498',
  'timestamp': 1695268728,
  'datetime': '2023-09-21T03:58:48+00:00',
  'operation': 'R',
  'author_name': 'Aakansha Doshi',
  'author_email': 'aakansha1216@gmail.com',
  'commit_subject': 'refactor: move excalidraw-app outside src (#6987)',
  'old_path': 'src/excalidraw-app/components/GitHubCorner.tsx',
  'similarity': 94}]

In [37]:
import pandas as pd

start_date = '2019-12-01'
end_date = '2026-01-31'

# Create weekly bins
weeks = pd.date_range(start=start_date, end=end_date, freq='W-MON')


# Create a DataFrame mapping
week_df = pd.DataFrame({'week_start': weeks})
week_df['year'] = week_df['week_start'].apply(lambda x: x.year)


def get_week_no(df, year):
    year_df = df[df['year'] == year].reset_index(drop=True)
    year_df['week_no'] = year_df.index + 1

    year_df['week_label'] = year_df.apply(lambda x: (x['year'], x['week_no']) ,axis=1)
    return dict(zip(year_df['week_start'], year_df['week_label']))
    
list_years = sorted(set(week_df['year']))
list_year_dicts = [get_week_no(week_df, year) for year in list_years]
dict_week_label = {}
for d in list_year_dicts:
    dict_week_label.update(d)

week_df['week_label'] = week_df['week_start'].apply(lambda x: dict_week_label[x])

In [38]:
week_df

    week_start  year  week_label
0   2019-12-02  2019   (2019, 1)
1   2019-12-09  2019   (2019, 2)
2   2019-12-16  2019   (2019, 3)
3   2019-12-23  2019   (2019, 4)
4   2019-12-30  2019   (2019, 5)
..         ...   ...         ...
317 2025-12-29  2025  (2025, 52)
318 2026-01-05  2026   (2026, 1)
319 2026-01-12  2026   (2026, 2)
320 2026-01-19  2026   (2026, 3)
321 2026-01-26  2026   (2026, 4)

[322 rows x 3 columns]

In [41]:
df_file_lifecycle['files'].iloc[0]

[{'commit_hash': 'b9a255407fc5e68893016de56057614da26df50c',
  'timestamp': 1768065314,
  'datetime': '2026-01-10T17:15:14+00:00',
  'operation': 'D',
  'author_name': 'David Luzar',
  'author_email': '5153846+dwelle@users.noreply.github.com',
  'commit_subject': 'refactor: update SCSS syntax & remove open-color dep (#10633)'},
 {'commit_hash': '432a46ef9ee13afe47530e857a259acde4d0fd59',
  'timestamp': 1742999099,
  'datetime': '2025-03-26T14:24:59+00:00',
  'operation': 'M',
  'author_name': 'Marcel Mraz',
  'author_email': 'marcel@excalidraw.com',
  'commit_subject': 'refactor: separate elements logic into a standalone package (#9285)'},
 {'commit_hash': '21ffaf4d76bf8554c3ba5561ab8ff41ce89b55fa',
  'timestamp': 1741789411,
  'datetime': '2025-03-12T14:23:31+00:00',
  'operation': 'M',
  'author_name': 'Marcel Mraz',
  'author_email': 'marcel@excalidraw.com',
  'commit_subject': 'refactor: auto ordered imports (#9163)'},
 {'commit_hash': 'ecef5d12f4af4f70e240fc54fb626c16d005eee3',
  'timestamp': 1740757749,
  'datetime': '2025-02-28T15:49:09+00:00',
  'operation': 'M',
  'author_name': 'Marcel Mraz',
  'author_email': 'marcel@excalidraw.com',
  'commit_subject': 'chore: release @excalidraw/excalidraw@18.0.0  🎉 (#9127)'},
 {'commit_hash': '1ed53b153cd09ef32e45304ab52b7d32fbe02605',
  'timestamp': 1715158310,
  'datetime': '2024-05-08T08:51:50+00:00',
  'operation': 'M',
  'author_name': 'Aakansha Doshi',
  'author_email': 'aakansha1216@gmail.com',
  'commit_subject': 'build: enable consistent type imports eslint rule (#7992)'},
 {'commit_hash': 'd6cd8b78f11742e9107dd4cd9cee564120ae599b',
  'timestamp': 1702360971,
  'datetime': '2023-12-12T06:02:51+00:00',
  'operation': 'M',
  'author_name': 'Aakansha Doshi',
  'author_email': 'aakansha1216@gmail.com',
  'commit_subject': 'build: decouple package deps and introduce yarn workspaces (#7415)'},
 {'commit_hash': '741d5f1a187438b46d4482cdc3ca0f8fde4f4498',
  'timestamp': 1695268728,
  'datetime': '2023-09-21T03:58:48+00:00',
  'operation': 'R',
  'author_name': 'Aakansha Doshi',
  'author_email': 'aakansha1216@gmail.com',
  'commit_subject': 'refactor: move excalidraw-app outside src (#6987)',
  'old_path': 'src/excalidraw-app/components/GitHubCorner.tsx',
  'similarity': 94}]